/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.7 */
/* Wed Jan 13 21:41:13 2021 */

/* parameterized module instance */
dynamic_pll __ (.CLKI( ), .PLLCLK( ), .PLLRST( ), .PLLSTB( ), .PLLWE( ), 
    .PLLDATI( ), .PLLADDR( ), .CLKOP( ), .LOCK( ), .PLLDATO( ), 
    .PLLACK( ));
