/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Sun Apr 11 02:49:54 2021 */

/* parameterized module instance */
dynamic_pll __ (.CLKI( ), .PLLCLK( ), .PLLRST( ), .PLLSTB( ), .PLLWE( ), 
    .PLLDATI( ), .PLLADDR( ), .CLKOP( ), .CLKOS( ), .LOCK( ), 
    .PLLDATO( ), .PLLACK( ));
