/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.7 */
/* Sat Feb 06 15:59:49 2021 */

/* parameterized module instance */
sys_clk __ (.CLKI( ), .CLKOP( ));
